### ISSUE TITLE
block stream lags and falls behind the slot progression

### ISSUE THREAD

**Issue by grooviegermanikus** [blockworks-foundation/geyser-grpc-connector#10]
### Problem
The full block stream cannot keep up with slot progression on the chain and also not with block meta sent via geyser.

Lag is approx 42 slots in 60 seconds (mainnet)!

**Did not observe that lag on testnet.**

### Investigation

> grpcurl  -proto geyser.proto -H "x-token: $MAINNET_API_TOKEN" -max-msg-sz 10000000 -format json -d @  <geyserhost>:443    geyser.Geyser.Subscribe <<EOM
{
  "accounts": {},
  "slots": {},
  "transactions": {},
  "blocks": {
    "block_client": {
      "account_include": [],
      "include_transactions": true,
      "include_accounts": false,
      "include_entries": false
    }
  },
  "blocks_meta": {},
  "entry": {}
}
EOM |  jq '.block.slot'

run `debug_blockstream_lag` against mainnet - make sure that the unpatched GrpcClient gets used in `create_geyser_reconnecting_stream:`

> 2024-03-25T11:01:09.907830Z  INFO debug_blockstream_lag: got block update (blue)!!! slot: 256337980    
2024-03-25T11:01:09.907839Z  INFO debug_blockstream_lag: **delta: 25**    
2024-03-25T11:01:10.036505Z TRACE geyser_grpc_connector::grpc_subscription_autoreconnect_streams: > recv update message from grpc_addr ...    
2024-03-25T11:01:10.036561Z  INFO debug_blockstream_lag: got block update (blue)!!! slot: 256337981    
2024-03-25T11:01:10.036569Z  INFO debug_blockstream_lag: **delta: 24**    
2024-03-25T11:01:10.153134Z TRACE geyser_grpc_connector::grpc_subscription_autoreconnect_streams: > recv update message from grpc_addr ....    
2024-03-25T11:01:10.153198Z  INFO debug_blockstream_lag: got blockmeta update (green)!!! slot: 256338006    
2024-03-25T11:01:10.307920Z TRACE geyser_grpc_connector::grpc_subscription_autoreconnect_streams: > recv update message from grpc_addr ...    
2024-03-25T11:01:10.307972Z  INFO debug_blockstream_lag: got block update (blue)!!! slot: 256337982

**Comment by grooviegermanikus** [comment]
there is an [h2 docs issue](https://github.com/hyperium/tonic/issues/1126) regarding `initial_connection_window_size` and `initial_stream_window_size` which is **NOT** defaulting to 65535 bytes but to 5mb and 2mb respectively (see [here](https://github.com/hyperium/hyper/blob/v0.14.28/src/proto/h2/client.rs#L45))

**Comment by grooviegermanikus** [comment]
the value px=>**99** is the slot delta between block meta and blocks

> endpoint config(default): EndpointConfig { buffer_size: 1024, initial_connection_window_size: 5242880, initial_stream_window_size: 2097152 }
> (5+ reconnects)
Histogram: p0=>5 p5=>16 p10=>23 p15.000001=>26 p20=>29 p25=>32 p30.000002=>37 p35=>46 p40=>52 p45=>54 p50=>56 p55=>58 p60.000004=>60 p65=>62 p70=>72 p75=>74 p80=>79 p85=>81 p90=>89 p95=>93 p100=>96   


> endpoint config: EndpointConfig { buffer_size: 65536, initial_connection_window_size: 5242880, initial_stream_window_size: 2097152 }  
Histogram: p0=>4 p5=>12 p10=>13 p15.000001=>14 p20=>18 p25=>23 p30.000002=>25 p35=>27 p40=>34 p45=>38 p50=>41 p55=>45 p60.000004=>47 p65=>49 p70=>50 p75=>51 p80=>51 p85=>52 p90=>52 p95=>53 p100=>54  


> endpoint config: EndpointConfig { buffer_size: 1024, initial_connection_window_size: 5242880, initial_stream_window_size: 4194304 }    
Histogram: p0=>0 p5=>0 p10=>0 p15.000001=>0 p20=>0 p25=>0 p30.000002=>0 p35=>0 p40=>0 p45=>0 p50=>0 p55=>1 p60.000004=>1 p65=>1 p70=>1 p75=>1 p80=>1 p85=>1 p90=>2 p95=>2 p100=>4


> endpoint config: EndpointConfig { buffer_size: 65536, initial_connection_window_size: 5242880, initial_stream_window_size: 4194304 }    
(1 reconnect)
Histogram: p0=>0 p5=>0 p10=>0 p15.000001=>0 p20=>0 p25=>0 p30.000002=>0 p35=>0 p40=>0 p45=>0 p50=>0 p55=>1 p60.000004=>1 p65=>1 p70=>1 p75=>2 p80=>2 p85=>3 p90=>4 p95=>5 p100=>6

**Comment by godmodegalactus** [comment]
Which machine did you did these tests on ?

**Comment by grooviegermanikus** [comment]
the effect is sensitive to network downstream speed -> on 10MB/s line it's very reproducible

**Comment by grooviegermanikus** [comment]
applied the window change
